/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _MOZILLA_CONFIG_H_
#define _MOZILLA_CONFIG_H_

#define ACCESSIBILITY 1
#define ATK_MAJOR_VERSION 1
#define ATK_MINOR_VERSION 24
#define ATK_REV_VERSION 0
#define BUILD_CTYPES 1
#define D_INO d_ino
#define ENABLE_SYSTEM_EXTENSION_DIRS 1
#define FIREFOX_VERSION 10.0.7
#define FUNCPROTO 15
#define HAVE_CLOCK_MONOTONIC 1
#define HAVE_DIRENT_H 1
#define HAVE_DLADDR 1
#define HAVE_DLOPEN 1
#define HAVE_FCHMOD 1
#define HAVE_FLOCKFILE 1
#define HAVE_FONTCONFIG_FCFREETYPE_H 1
#define HAVE_FT_BITMAP_SIZE_Y_PPEM 1
#define HAVE_FT_GLYPHSLOT_EMBOLDEN 1
#define HAVE_FT_LOAD_SFNT_TABLE 1
#define HAVE_GETOPT_H 1
#define HAVE_I18N_LC_MESSAGES 1
#define HAVE_INT16_T 1
#define HAVE_INT32_T 1
#define HAVE_INT64_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_ISATTY 1
#define HAVE_JEMALLOC_MEMALIGN 1
#define HAVE_JEMALLOC_POSIX_MEMALIGN 1
#define HAVE_JEMALLOC_VALLOC 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LCHOWN 1
#define HAVE_LIBSOCKET 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LSTAT64 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_MMINTRIN_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_RANDOM 1
#define HAVE_SETBUF 1
#define HAVE_SNPRINTF 1
#define HAVE_SSIZE_T 1
#define HAVE_STAT64 1
#define HAVE_STDINT_H 1
#define HAVE_STRERROR 1
#define HAVE_STRTOK_R 1
#define HAVE_ST_BLKSIZE 1
#define HAVE_SYS_INT_TYPES_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_SYSMACROS_H 1
#define HAVE_THREAD_TLS_KEYWORD 1
#define HAVE_TRUNCATE64 1
#define HAVE_UINT 1
#define HAVE_UINT16_T 1
#define HAVE_UINT64_T 1
#define HAVE_UINT_T 1
#define HAVE_UNISTD_H 1
#define HAVE_VALLOC 1
#define HAVE_VA_COPY 1
#define IBMBIDI 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define LIBJPEG_TURBO_X86_ASM 1
#define MALLOC_H <malloc.h>
#define MOZILLA_VERSION "10.0.7"
#define MOZILLA_VERSION_U 10.0.7
#define MOZ_ACCESSIBILITY_ATK 1
#define MOZ_APP_UA_NAME ""
#define MOZ_APP_UA_VERSION "10.0.7"
#define MOZ_BUILD_APP browser
#define MOZ_CRASHREPORTER_ENABLE_PERCENT 100
#define MOZ_DISTRIBUTION_ID "org.mozilla"
#define MOZ_DLL_SUFFIX ".so"
#define MOZ_ENABLE_DBUS 1
#define MOZ_ENABLE_GCONF 1
#define MOZ_ENABLE_GNOMEUI 1
#define MOZ_ENABLE_GNOMEVFS 1
#define MOZ_ENABLE_XREMOTE 1
#define MOZ_FEEDS 1
#define MOZ_INSTRUMENT_EVENT_LOOP 1
#define MOZ_LOGGING 1
#define MOZ_MEDIA 1
#define MOZ_MEMORY 1
#define MOZ_MEMORY_SIZEOF_PTR_2POW 2
#define MOZ_MEMORY_SOLARIS 1
#define MOZ_OFFICIAL_BRANDING 1
#define MOZ_OGG 1
#define MOZ_OMNIJAR 1
#define MOZ_PANGO 1
#define MOZ_PDF_PRINTING 1
#define MOZ_PHOENIX 1
#define MOZ_PLACES 1
#define MOZ_PROFILELOCKING 1
#define MOZ_SAFE_BROWSING 1
#define MOZ_SERVICES_SYNC 1
#define MOZ_STATIC_JS 1
#define MOZ_SYDNEYAUDIO 1
#define MOZ_TREE_CAIRO 1
#define MOZ_TREE_PIXMAN 1
#define MOZ_UA_BUILDID "20100101"
#define MOZ_UA_FIREFOX_VERSION "10.0.7"
#define MOZ_UPDATE_CHANNEL default
#define MOZ_URL_CLASSIFIER 1
#define MOZ_USER_DIR ".mozilla"
#define MOZ_VORBIS 1
#define MOZ_WAVE 1
#define MOZ_WEBM 1
#define MOZ_WIDGET_GTK2 1
#define MOZ_X11 1
#define MOZ_XTF 1
#define MOZ_XUL 1
#define NSCAP_DISABLE_DEBUG_PTR_TYPES 1
#define NS_ALWAYS_INLINE __attribute__((always_inline))
#define NS_ATTR_MALLOC __attribute__((malloc))
#define NS_NORETURN __attribute__((noreturn))
#define NS_PRINTING 1
#define NS_PRINT_PREVIEW 1
#define NS_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#define SIZEOF_INT_P 4
#define SOLARIS 1
#define STDC_HEADERS 1
#define UNIX_ASYNC_DNS 1
#define VA_COPY va_copy
#define VPX_X86_ASM 1
#define XP_UNIX 1
#define _REENTRANT 1

/* The c99 defining the limit macros (UINT32_MAX for example), says:
 * C++ implementations should define these macros only when __STDC_LIMIT_MACROS
 * is defined before <stdint.h> is included. */
#define __STDC_LIMIT_MACROS

/* Force-include hunspell_alloc_hooks.h for hunspell, so that we don't need to
 * modify it directly.
 *
 * HUNSPELL_STATIC is defined in extensions/spellcheck/hunspell/src/Makefile.in,
 * unless --enable-system-hunspell is defined.
 */
#if defined(HUNSPELL_STATIC)
#include "hunspell_alloc_hooks.h"
#endif

#endif /* _MOZILLA_CONFIG_H_ */

