/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */
#ifndef Accessibility_LoginHelper_H
#define Accessibility_LoginHelper_H 1
#include <glib.h>
#define ORBIT_IDL_SERIAL 20
#include <orbit/orbit-types.h>
#ifdef __cplusplus
extern "C" {
#endif				/* __cplusplus */
   /** typedefs **/
#include <bonobo-activation/Bonobo_Unknown.h>
#if !defined(ORBIT_DECL_Accessibility_LoginHelper) && !defined(_Accessibility_LoginHelper_defined)
#define ORBIT_DECL_Accessibility_LoginHelper 1
#define _Accessibility_LoginHelper_defined 1
#define Accessibility_LoginHelper__freekids CORBA_Object__freekids
   typedef CORBA_Object Accessibility_LoginHelper;
   extern CORBA_unsigned_long Accessibility_LoginHelper__classid;
#if !defined(TC_IMPL_TC_Accessibility_LoginHelper_0)
#define TC_IMPL_TC_Accessibility_LoginHelper_0 'A'
#define TC_IMPL_TC_Accessibility_LoginHelper_1 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_2 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_3 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_4 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_5 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_6 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_7 'b'
#define TC_IMPL_TC_Accessibility_LoginHelper_8 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_9 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_10 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_11 't'
#define TC_IMPL_TC_Accessibility_LoginHelper_12 'y'
#define TC_IMPL_TC_Accessibility_LoginHelper_13 '_'
#define TC_IMPL_TC_Accessibility_LoginHelper_14 'L'
#define TC_IMPL_TC_Accessibility_LoginHelper_15 'o'
#define TC_IMPL_TC_Accessibility_LoginHelper_16 'g'
#define TC_IMPL_TC_Accessibility_LoginHelper_17 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_18 'n'
#define TC_IMPL_TC_Accessibility_LoginHelper_19 'H'
#define TC_IMPL_TC_Accessibility_LoginHelper_20 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_21 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_22 'p'
#define TC_IMPL_TC_Accessibility_LoginHelper_23 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_24 'r'
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   const struct CORBA_TypeCode_struct TC_Accessibility_LoginHelper_struct;
#define TC_Accessibility_LoginHelper ((CORBA_TypeCode)&TC_Accessibility_LoginHelper_struct)
#endif
#endif
#if !defined(_Accessibility_LoginHelper_WindowInfo_defined)
#define _Accessibility_LoginHelper_WindowInfo_defined 1
   typedef struct Accessibility_LoginHelper_WindowInfo_type Accessibility_LoginHelper_WindowInfo;
   struct Accessibility_LoginHelper_WindowInfo_type {
      CORBA_long winID;
   };
#if !defined(TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_0)
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_0 'A'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_1 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_2 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_3 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_4 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_5 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_6 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_7 'b'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_8 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_9 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_10 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_11 't'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_12 'y'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_13 '_'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_14 'L'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_15 'o'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_16 'g'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_17 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_18 'n'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_19 'H'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_20 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_21 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_22 'p'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_23 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowInfo_24 'r'
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   const struct CORBA_TypeCode_struct TC_Accessibility_LoginHelper_WindowInfo_struct;
#define TC_Accessibility_LoginHelper_WindowInfo ((CORBA_TypeCode)&TC_Accessibility_LoginHelper_WindowInfo_struct)
#endif
#define Accessibility_LoginHelper_WindowInfo__alloc() ((Accessibility_LoginHelper_WindowInfo *)ORBit_small_alloc (TC_Accessibility_LoginHelper_WindowInfo))
#define Accessibility_LoginHelper_WindowInfo__freekids(m,d) ORBit_small_freekids (TC_Accessibility_LoginHelper_WindowInfo,(m),(d))
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo)
#define ORBIT_DECL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo 1
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_0 'A'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_1 'c'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_2 'c'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_3 'e'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_4 's'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_5 's'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_6 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_7 'b'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_8 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_9 'l'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_10 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_11 't'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_12 'y'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_13 '_'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_14 'L'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_15 'o'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_16 'g'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_17 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_18 'n'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_19 'H'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_20 'e'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_21 'l'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_22 'p'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_23 'e'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_24 'r'
#if !defined(_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_defined)
#define _CORBA_sequence_Accessibility_LoginHelper_WindowInfo_defined 1
   typedef struct {
      CORBA_unsigned_long _maximum,
       _length;
      Accessibility_LoginHelper_WindowInfo *_buffer;
      CORBA_boolean _release;
   } CORBA_sequence_Accessibility_LoginHelper_WindowInfo;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_0)
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_0 'A'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_1 'c'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_2 'c'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_3 'e'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_4 's'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_5 's'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_6 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_7 'b'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_8 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_9 'l'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_10 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_11 't'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_12 'y'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_13 '_'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_14 'L'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_15 'o'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_16 'g'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_17 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_18 'n'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_19 'H'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_20 'e'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_21 'l'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_22 'p'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_23 'e'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_24 'r'
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   const struct CORBA_TypeCode_struct TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_struct;
#define TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo ((CORBA_TypeCode)&TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo_struct)
#endif
#define CORBA_sequence_Accessibility_LoginHelper_WindowInfo__alloc() ((CORBA_sequence_Accessibility_LoginHelper_WindowInfo *)ORBit_small_alloc (TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo))
#define CORBA_sequence_Accessibility_LoginHelper_WindowInfo__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo,(m),(d))
#define CORBA_sequence_Accessibility_LoginHelper_WindowInfo_allocbuf(l) ((Accessibility_LoginHelper_WindowInfo*)ORBit_small_allocbuf (TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo, (l)))
#define CORBA_sequence_Accessibility_LoginHelper_WindowInfo_allocbuf(l) ((Accessibility_LoginHelper_WindowInfo*)ORBit_small_allocbuf (TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo, (l)))
#endif
#if !defined(_Accessibility_LoginHelper_WindowList_defined)
#define _Accessibility_LoginHelper_WindowList_defined 1
   typedef CORBA_sequence_Accessibility_LoginHelper_WindowInfo Accessibility_LoginHelper_WindowList;
#define Accessibility_LoginHelper_WindowList_marshal(x,y,z) CORBA_sequence_Accessibility_LoginHelper_WindowInfo_marshal((x),(y),(z))
#define Accessibility_LoginHelper_WindowList_demarshal(x,y,z,i) CORBA_sequence_Accessibility_LoginHelper_WindowInfo_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Accessibility_LoginHelper_WindowList_0)
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_0 'A'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_1 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_2 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_3 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_4 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_5 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_6 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_7 'b'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_8 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_9 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_10 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_11 't'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_12 'y'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_13 '_'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_14 'L'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_15 'o'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_16 'g'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_17 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_18 'n'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_19 'H'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_20 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_21 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_22 'p'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_23 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_WindowList_24 'r'
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   const struct CORBA_TypeCode_struct TC_Accessibility_LoginHelper_WindowList_struct;
#define TC_Accessibility_LoginHelper_WindowList ((CORBA_TypeCode)&TC_Accessibility_LoginHelper_WindowList_struct)
#endif
#define Accessibility_LoginHelper_WindowList__alloc() ((Accessibility_LoginHelper_WindowList *)ORBit_small_alloc (TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo))
#define Accessibility_LoginHelper_WindowList__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo,(m),(d))
#define Accessibility_LoginHelper_WindowList_allocbuf(l) ((Accessibility_LoginHelper_WindowInfo*)ORBit_small_allocbuf (TC_CORBA_sequence_Accessibility_LoginHelper_WindowInfo, (l)))
#endif
#if !defined(_Accessibility_LoginHelper_DeviceReq_defined)
#define _Accessibility_LoginHelper_DeviceReq_defined 1
   typedef enum {
      Accessibility_LoginHelper_GUI_EVENTS,
      Accessibility_LoginHelper_CORE_KEYBOARD,
      Accessibility_LoginHelper_CORE_POINTER,
      Accessibility_LoginHelper_EXT_INPUT,
      Accessibility_LoginHelper_POST_WINDOWS,
      Accessibility_LoginHelper_AUDIO_OUT,
      Accessibility_LoginHelper_AUDIO_IN,
      Accessibility_LoginHelper_NETWORK,
      Accessibility_LoginHelper_LOCALHOST,
      Accessibility_LoginHelper_SERIAL_OUT,
      Accessibility_LoginHelper_SERIAL_IN
   } Accessibility_LoginHelper_DeviceReq;
#if !defined(TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_0)
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_0 'A'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_1 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_2 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_3 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_4 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_5 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_6 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_7 'b'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_8 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_9 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_10 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_11 't'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_12 'y'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_13 '_'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_14 'L'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_15 'o'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_16 'g'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_17 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_18 'n'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_19 'H'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_20 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_21 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_22 'p'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_23 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReq_24 'r'
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   const struct CORBA_TypeCode_struct TC_Accessibility_LoginHelper_DeviceReq_struct;
#define TC_Accessibility_LoginHelper_DeviceReq ((CORBA_TypeCode)&TC_Accessibility_LoginHelper_DeviceReq_struct)
#endif
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq)
#define ORBIT_DECL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq 1
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_0 'A'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_1 'c'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_2 'c'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_3 'e'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_4 's'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_5 's'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_6 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_7 'b'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_8 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_9 'l'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_10 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_11 't'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_12 'y'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_13 '_'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_14 'L'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_15 'o'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_16 'g'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_17 'i'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_18 'n'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_19 'H'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_20 'e'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_21 'l'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_22 'p'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_23 'e'
#define ORBIT_IMPL_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_24 'r'
#if !defined(_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_defined)
#define _CORBA_sequence_Accessibility_LoginHelper_DeviceReq_defined 1
   typedef struct {
      CORBA_unsigned_long _maximum,
       _length;
      Accessibility_LoginHelper_DeviceReq *_buffer;
      CORBA_boolean _release;
   } CORBA_sequence_Accessibility_LoginHelper_DeviceReq;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_0)
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_0 'A'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_1 'c'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_2 'c'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_3 'e'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_4 's'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_5 's'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_6 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_7 'b'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_8 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_9 'l'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_10 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_11 't'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_12 'y'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_13 '_'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_14 'L'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_15 'o'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_16 'g'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_17 'i'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_18 'n'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_19 'H'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_20 'e'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_21 'l'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_22 'p'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_23 'e'
#define TC_IMPL_TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_24 'r'
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   const struct CORBA_TypeCode_struct TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_struct;
#define TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq ((CORBA_TypeCode)&TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq_struct)
#endif
#define CORBA_sequence_Accessibility_LoginHelper_DeviceReq__alloc() ((CORBA_sequence_Accessibility_LoginHelper_DeviceReq *)ORBit_small_alloc (TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq))
#define CORBA_sequence_Accessibility_LoginHelper_DeviceReq__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq,(m),(d))
#define CORBA_sequence_Accessibility_LoginHelper_DeviceReq_allocbuf(l) ((Accessibility_LoginHelper_DeviceReq*)ORBit_small_allocbuf (TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq, (l)))
#define CORBA_sequence_Accessibility_LoginHelper_DeviceReq_allocbuf(l) ((Accessibility_LoginHelper_DeviceReq*)ORBit_small_allocbuf (TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq, (l)))
#endif
#if !defined(_Accessibility_LoginHelper_DeviceReqList_defined)
#define _Accessibility_LoginHelper_DeviceReqList_defined 1
   typedef CORBA_sequence_Accessibility_LoginHelper_DeviceReq Accessibility_LoginHelper_DeviceReqList;
#define Accessibility_LoginHelper_DeviceReqList_marshal(x,y,z) CORBA_sequence_Accessibility_LoginHelper_DeviceReq_marshal((x),(y),(z))
#define Accessibility_LoginHelper_DeviceReqList_demarshal(x,y,z,i) CORBA_sequence_Accessibility_LoginHelper_DeviceReq_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_0)
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_0 'A'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_1 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_2 'c'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_3 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_4 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_5 's'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_6 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_7 'b'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_8 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_9 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_10 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_11 't'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_12 'y'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_13 '_'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_14 'L'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_15 'o'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_16 'g'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_17 'i'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_18 'n'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_19 'H'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_20 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_21 'l'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_22 'p'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_23 'e'
#define TC_IMPL_TC_Accessibility_LoginHelper_DeviceReqList_24 'r'
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   const struct CORBA_TypeCode_struct TC_Accessibility_LoginHelper_DeviceReqList_struct;
#define TC_Accessibility_LoginHelper_DeviceReqList ((CORBA_TypeCode)&TC_Accessibility_LoginHelper_DeviceReqList_struct)
#endif
#define Accessibility_LoginHelper_DeviceReqList__alloc() ((Accessibility_LoginHelper_DeviceReqList *)ORBit_small_alloc (TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq))
#define Accessibility_LoginHelper_DeviceReqList__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq,(m),(d))
#define Accessibility_LoginHelper_DeviceReqList_allocbuf(l) ((Accessibility_LoginHelper_DeviceReq*)ORBit_small_allocbuf (TC_CORBA_sequence_Accessibility_LoginHelper_DeviceReq, (l)))
#endif
   /** POA structures **/
#ifndef _defined_POA_Accessibility_LoginHelper
#define _defined_POA_Accessibility_LoginHelper 1
   typedef struct {
      void *_private;
       CORBA_boolean(*setSafe) (PortableServer_Servant _servant, const CORBA_boolean safe_mode, CORBA_Environment * ev);
      Accessibility_LoginHelper_DeviceReqList *(*getDeviceReqs) (PortableServer_Servant _servant, CORBA_Environment * ev);
      Accessibility_LoginHelper_WindowList *(*getRaiseWindows) (PortableServer_Servant _servant, CORBA_Environment * ev);
      void (*unImplemented) (PortableServer_Servant _servant, CORBA_Environment * ev);
      void (*unImplemented2) (PortableServer_Servant _servant, CORBA_Environment * ev);
      void (*unImplemented3) (PortableServer_Servant _servant, CORBA_Environment * ev);
      void (*unImplemented4) (PortableServer_Servant _servant, CORBA_Environment * ev);
   } POA_Accessibility_LoginHelper__epv;
   typedef struct {
      PortableServer_ServantBase__epv *_base_epv;
      POA_Bonobo_Unknown__epv *Bonobo_Unknown_epv;
      POA_Accessibility_LoginHelper__epv *Accessibility_LoginHelper_epv;
   } POA_Accessibility_LoginHelper__vepv;
   typedef struct {
      void *_private;
      POA_Accessibility_LoginHelper__vepv *vepv;
   } POA_Accessibility_LoginHelper;
   extern void POA_Accessibility_LoginHelper__init(PortableServer_Servant servant, CORBA_Environment * ev);
   extern void POA_Accessibility_LoginHelper__fini(PortableServer_Servant servant, CORBA_Environment * ev);
#endif				/* _defined_POA_Accessibility_LoginHelper */
   /** skel prototypes **/
   void _ORBIT_skel_small_Accessibility_LoginHelper_setSafe(POA_Accessibility_LoginHelper * _ORBIT_servant, gpointer _ORBIT_retval, gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev, CORBA_boolean(*_impl_setSafe) (PortableServer_Servant _servant, const CORBA_boolean safe_mode, CORBA_Environment * ev));
   void _ORBIT_skel_small_Accessibility_LoginHelper_getDeviceReqs(POA_Accessibility_LoginHelper * _ORBIT_servant, gpointer _ORBIT_retval, gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev, Accessibility_LoginHelper_DeviceReqList * (*_impl_getDeviceReqs) (PortableServer_Servant _servant, CORBA_Environment * ev));
   void _ORBIT_skel_small_Accessibility_LoginHelper_getRaiseWindows(POA_Accessibility_LoginHelper * _ORBIT_servant, gpointer _ORBIT_retval, gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev, Accessibility_LoginHelper_WindowList * (*_impl_getRaiseWindows) (PortableServer_Servant _servant, CORBA_Environment * ev));
   void _ORBIT_skel_small_Accessibility_LoginHelper_unImplemented(POA_Accessibility_LoginHelper * _ORBIT_servant, gpointer _ORBIT_retval, gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev, void (*_impl_unImplemented) (PortableServer_Servant _servant, CORBA_Environment * ev));
   void _ORBIT_skel_small_Accessibility_LoginHelper_unImplemented2(POA_Accessibility_LoginHelper * _ORBIT_servant, gpointer _ORBIT_retval, gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev, void (*_impl_unImplemented2) (PortableServer_Servant _servant, CORBA_Environment * ev));
   void _ORBIT_skel_small_Accessibility_LoginHelper_unImplemented3(POA_Accessibility_LoginHelper * _ORBIT_servant, gpointer _ORBIT_retval, gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev, void (*_impl_unImplemented3) (PortableServer_Servant _servant, CORBA_Environment * ev));
   void _ORBIT_skel_small_Accessibility_LoginHelper_unImplemented4(POA_Accessibility_LoginHelper * _ORBIT_servant, gpointer _ORBIT_retval, gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev, void (*_impl_unImplemented4) (PortableServer_Servant _servant, CORBA_Environment * ev));
   /** stub prototypes **/
#define Accessibility_LoginHelper_ref Bonobo_Unknown_ref
#define Accessibility_LoginHelper_unref Bonobo_Unknown_unref
#define Accessibility_LoginHelper_queryInterface Bonobo_Unknown_queryInterface
   CORBA_boolean Accessibility_LoginHelper_setSafe(Accessibility_LoginHelper _obj, const CORBA_boolean safe_mode, CORBA_Environment * ev);
   Accessibility_LoginHelper_DeviceReqList *Accessibility_LoginHelper_getDeviceReqs(Accessibility_LoginHelper _obj, CORBA_Environment * ev);
   Accessibility_LoginHelper_WindowList *Accessibility_LoginHelper_getRaiseWindows(Accessibility_LoginHelper _obj, CORBA_Environment * ev);
   void Accessibility_LoginHelper_unImplemented(Accessibility_LoginHelper _obj, CORBA_Environment * ev);
   void Accessibility_LoginHelper_unImplemented2(Accessibility_LoginHelper _obj, CORBA_Environment * ev);
   void Accessibility_LoginHelper_unImplemented3(Accessibility_LoginHelper _obj, CORBA_Environment * ev);
   void Accessibility_LoginHelper_unImplemented4(Accessibility_LoginHelper _obj, CORBA_Environment * ev);
#include <orbit/orb-core/orbit-interface.h>
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   ORBit_IInterface Accessibility_LoginHelper__iinterface;
#define Accessibility_LoginHelper_IMETHODS_LEN 7
#ifdef ORBIT_IDL_C_IMODULE_Accessibility_LoginHelper
   static
#else
   extern
#endif
   ORBit_IMethod Accessibility_LoginHelper__imethods[Accessibility_LoginHelper_IMETHODS_LEN];
#ifdef __cplusplus
}
#endif				/* __cplusplus */
#ifndef EXCLUDE_ORBIT_H
#include <orbit/orbit.h>
#endif				/* EXCLUDE_ORBIT_H */
#endif
#undef ORBIT_IDL_SERIAL
