/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFSAUTH_PROT_H_RPCGEN
#define	_NFSAUTH_PROT_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#pragma ident	"@(#)nfsauth_prot.x	1.11	04/05/07 SMI"
#define	A_MAXPATH 1024

struct auth_req {
	netobj req_client;
	char *req_netid;
	char *req_path;
	int req_flavor;
};
typedef struct auth_req auth_req;
#define	NFSAUTH_DENIED 0x01
#define	NFSAUTH_RO 0x02
#define	NFSAUTH_RW 0x04
#define	NFSAUTH_ROOT 0x08
#define	NFSAUTH_WRONGSEC 0x10
#define	NFSAUTH_DROP 0x20
#define	NFSAUTH_MAPNONE 0x40
#define	NFSAUTH_LIMITED 0x80

struct auth_res {
	int auth_perm;
};
typedef struct auth_res auth_res;

#define	NFSAUTH_PROG	100231
#define	NFSAUTH_VERS	1

#if defined(__STDC__) || defined(__cplusplus)
#define	NFSAUTH_ACCESS	1
extern  auth_res * nfsauth_access_1(auth_req *, CLIENT *);
extern  auth_res * nfsauth_access_1_svc(auth_req *, struct svc_req *);
extern int nfsauth_prog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	NFSAUTH_ACCESS	1
extern  auth_res * nfsauth_access_1();
extern  auth_res * nfsauth_access_1_svc();
extern int nfsauth_prog_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_auth_req(XDR *, auth_req*);
extern  bool_t xdr_auth_res(XDR *, auth_res*);

#else /* K&R C */
extern bool_t xdr_auth_req();
extern bool_t xdr_auth_res();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFSAUTH_PROT_H_RPCGEN */
