/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NIS_CALLBACK_H_RPCGEN
#define	_NIS_CALLBACK_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#pragma ident	"@(#)nis_callback.x	1.4	92/07/14 SMI"
#include <rpcsvc/nis.h>

typedef nis_object *obj_p;

struct cback_data {
	struct {
		u_int entries_len;
		obj_p *entries_val;
	} entries;
};
typedef struct cback_data cback_data;

#define	CB_PROG	100302
#define	CB_VERS	1

#if defined(__STDC__) || defined(__cplusplus)
#define	CBPROC_RECEIVE	1
extern  bool_t * cbproc_receive_1(cback_data *, CLIENT *);
extern  bool_t * cbproc_receive_1_svc(cback_data *, struct svc_req *);
#define	CBPROC_FINISH	2
extern  void * cbproc_finish_1(void *, CLIENT *);
extern  void * cbproc_finish_1_svc(void *, struct svc_req *);
#define	CBPROC_ERROR	3
extern  void * cbproc_error_1(nis_error *, CLIENT *);
extern  void * cbproc_error_1_svc(nis_error *, struct svc_req *);
extern int cb_prog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	CBPROC_RECEIVE	1
extern  bool_t * cbproc_receive_1();
extern  bool_t * cbproc_receive_1_svc();
#define	CBPROC_FINISH	2
extern  void * cbproc_finish_1();
extern  void * cbproc_finish_1_svc();
#define	CBPROC_ERROR	3
extern  void * cbproc_error_1();
extern  void * cbproc_error_1_svc();
extern int cb_prog_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_obj_p(XDR *, obj_p*);
extern  bool_t xdr_cback_data(XDR *, cback_data*);

#else /* K&R C */
extern bool_t xdr_obj_p();
extern bool_t xdr_cback_data();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NIS_CALLBACK_H_RPCGEN */
