/*
 * Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */

#ifndef	_SYS_FM_IO_SCSI_H
#define	_SYS_FM_IO_SCSI_H

#pragma ident	"@(#)scsi.h	1.1	08/01/21 SMI"

#ifdef	__cplusplus
extern "C" {
#endif

/*
 * The following ereports are generated by the userland disk-transport module in
 * response to errors reported by the disks.
 */
#define	SCSI_ERROR_CLASS		"io.scsi"

#define	SCSI_DISK_CLASS			"disk"

#define	FM_EREPORT_SCSI_PREDFAIL	"predictive-failure"
#define	FM_EREPORT_PAYLOAD_SCSI_ASC	"additional-sense-code"
#define	FM_EREPORT_PAYLOAD_SCSI_ASCQ	"additional-sense-code-qualifier"

#define	FM_EREPORT_SCSI_OVERTEMP		"over-temperature"
#define	FM_EREPORT_PAYLOAD_SCSI_CURTEMP		"current-temperature"
#define	FM_EREPORT_PAYLOAD_SCSI_THRESHTEMP	"threshold-temperature"

#define	FM_EREPORT_SCSI_TESTFAIL		"self-test-failure"
#define	FM_EREPORT_PAYLOAD_SCSI_RESULTCODE	"result-code"
#define	FM_EREPORT_PAYLOAD_SCSI_ADDRESS		"address"
#define	FM_EREPORT_PAYLOAD_SCSI_TIMESTAMP	"timestamp"
#define	FM_EREPORT_PAYLOAD_SCSI_SEGMENT		"segment"

#ifdef	__cplusplus
}
#endif

#endif	/* _SYS_FM_IO_SCSI_H */
