/*
 * Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
 */

#ifndef _SYS_PCI_PARAM_H
#define	_SYS_PCI_PARAM_H

#pragma ident	"@(#)pci_param.h	1.1	11/10/11 SMI"

#include <sys/dditypes.h>
#include <sys/ddipropdefs.h>
#include <sys/nvpair.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define	PCI_PARAM_DATA_TYPE_UNKNOWN		DATA_TYPE_UNKNOWN
#define	PCI_PARAM_DATA_TYPE_BOOLEAN		DATA_TYPE_BOOLEAN
#define	PCI_PARAM_DATA_TYPE_BYTE		DATA_TYPE_BYTE
#define	PCI_PARAM_DATA_TYPE_INT8		DATA_TYPE_INT8
#define	PCI_PARAM_DATA_TYPE_UINT8		DATA_TYPE_UINT8
#define	PCI_PARAM_DATA_TYPE_INT16		DATA_TYPE_INT16
#define	PCI_PARAM_DATA_TYPE_UINT16		DATA_TYPE_UINT16
#define	PCI_PARAM_DATA_TYPE_INT32		DATA_TYPE_INT32
#define	PCI_PARAM_DATA_TYPE_UINT32		DATA_TYPE_UINT32
#define	PCI_PARAM_DATA_TYPE_INT64		DATA_TYPE_INT64
#define	PCI_PARAM_DATA_TYPE_UINT64		DATA_TYPE_UINT64
#define	PCI_PARAM_DATA_TYPE_STRING		DATA_TYPE_STRING
#define	PCI_PARAM_DATA_TYPE_PLIST		DATA_TYPE_NVLIST
#define	PCI_PARAM_DATA_TYPE_BYTE_ARRAY		DATA_TYPE_BYTE_ARRAY
#define	PCI_PARAM_DATA_TYPE_INT8_ARRAY		DATA_TYPE_INT8_ARRAY
#define	PCI_PARAM_DATA_TYPE_UINT8_ARRAY		DATA_TYPE_UINT8_ARRAY
#define	PCI_PARAM_DATA_TYPE_INT16_ARRAY		DATA_TYPE_INT16_ARRAY
#define	PCI_PARAM_DATA_TYPE_UINT16_ARRAY	DATA_TYPE_UINT16_ARRAY
#define	PCI_PARAM_DATA_TYPE_INT32_ARRAY		DATA_TYPE_INT32_ARRAY
#define	PCI_PARAM_DATA_TYPE_UINT32_ARRAY	DATA_TYPE_UINT32_ARRAY
#define	PCI_PARAM_DATA_TYPE_INT64_ARRAY		DATA_TYPE_INT64_ARRAY
#define	PCI_PARAM_DATA_TYPE_UINT64_ARRAY	DATA_TYPE_UINT64_ARRAY
#define	PCI_PARAM_DATA_TYPE_STRING_ARRAY	DATA_TYPE_STRING_ARRAY
#define	PCI_PARAM_DATA_TYPE_PLIST_ARRAY		DATA_TYPE_NVLIST_ARRAY


#ifdef	__cplusplus
}
#endif

#endif	/* _SYS_PCI_PARAM_H */
